revision: 20210401
versions:
  v0.4.0:
    - 0.4.0
  0.3.1:
    - latest
    - 0.3.1
    - 0.3
  0.3.0:
    - 0.3.0
registries:
  docker.io:
    user_variable: DOCKER_USERNAME
    password_variable: DOCKER_PASSWORD
  quay.io:
    user_variable: QUAY_USERNAME
    password_variable: QUAY_PASSWORD
