revision: 20230630
versions:
  v0.5.0-alpha.1:
    - 0.5.0-alpha.1
  v0.4.1:
    - latest
    - 0.4.1
    - 0.4
  v0.4.0:
    - 0.4.0
  0.3.1:
    - 0.3.1
    - 0.3
  0.3.0:
    - 0.3.0
registries:
  docker.io:
    user_variable: DOCKER_USERNAME
    password_variable: DOCKER_PASSWORD
  quay.io:
    user_variable: QUAY_USERNAME
    password_variable: QUAY_PASSWORD
