revision: 20210525
versions:
  v0.4.1-alpha.2:
    - 0.4.1-alpha.2
  v0.4.0:
    - latest
    - 0.4.0
    - 0.4
  0.3.1:
    - 0.3.1
    - 0.3
  0.3.0:
    - 0.3.0
registries:
  docker.io:
    user_variable: DOCKER_USERNAME
    password_variable: DOCKER_PASSWORD
  quay.io:
    user_variable: QUAY_USERNAME
    password_variable: QUAY_PASSWORD
