name: Build
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: go run build.go
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
